export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰" },
  { name: "United States", code: "US", flag: "🇺🇸" },
  { name: "India", code: "IN", flag: "🇮🇳" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪" },
  { name: "Qatar", code: "QA", flag: "🇶🇦" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
  { name: "Singapore", code: "SG", flag: "🇸🇬" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾" },
  { name: "Canada", code: "CA", flag: "🇨🇦" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩" },
  { name: "Maldives", code: "MV", flag: "🇲🇻" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼" },
  { name: "Oman", code: "OM", flag: "🇴🇲" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭" },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Italy", code: "IT", flag: "🇮🇹" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭" },
  { name: "Ireland", code: "IE", flag: "🇮🇪" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿" },
  { name: "Japan", code: "JP", flag: "🇯🇵" },
  { name: "South Korea", code: "KR", flag: "🇰🇷" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬" },
  { name: "Kenya", code: "KE", flag: "🇰🇪" },
  { name: "Egypt", code: "EG", flag: "🇪🇬" },
  { name: "Ghana", code: "GH", flag: "🇬🇭" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾" },
  { name: "Greece", code: "GR", flag: "🇬🇷" },
  { name: "Turkey", code: "TR", flag: "🇹🇷" },
  { name: "Jordan", code: "JO", flag: "🇯🇴" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧" },
  { name: "Nepal", code: "NP", flag: "🇳🇵" },
  { name: "Thailand", code: "TH", flag: "🇹🇭" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩" },
  { name: "Philippines", code: "PH", flag: "🇵🇭" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "Mexico", code: "MX", flag: "🇲🇽" },
  { name: "Argentina", code: "AR", flag: "🇦🇷" },
  { name: "Chile", code: "CL", flag: "🇨🇱" },
  { name: "Colombia", code: "CO", flag: "🇨🇴" },
  { name: "Peru", code: "PE", flag: "🇵🇪" },
  { name: "Poland", code: "PL", flag: "🇵🇱" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Norway", code: "NO", flag: "🇳🇴" },
  { name: "Denmark", code: "DK", flag: "🇩🇰" },
  { name: "Finland", code: "FI", flag: "🇫🇮" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Romania", code: "RO", flag: "🇷🇴" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦" },
  { name: "Russia", code: "RU", flag: "🇷🇺" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿" },
  { name: "Georgia", code: "GE", flag: "🇬🇪" },
  { name: "Armenia", code: "AM", flag: "🇦🇲" },
  { name: "Israel", code: "IL", flag: "🇮🇱" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶" },
  { name: "Iran", code: "IR", flag: "🇮🇷" },
  { name: "Morocco", code: "MA", flag: "🇲🇦" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { name: "Uganda", code: "UG", flag: "🇺🇬" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲" },
  { name: "Botswana", code: "BW", flag: "🇧🇼" },
  { name: "Namibia", code: "NA", flag: "🇳🇦" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲" },
  { name: "Barbados", code: "BB", flag: "🇧🇧" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯" },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬" },
  { name: "Brunei", code: "BN", flag: "🇧🇳" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳" },
  { name: "Iceland", code: "IS", flag: "🇮🇸" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { name: "Malta", code: "MT", flag: "🇲🇹" },
];

export function findCountry(query: string): Country | undefined {
  if (!query) return undefined;
  const q = query.trim().toLowerCase();
  return COUNTRIES.find(
    (c) =>
      c.name.toLowerCase() === q ||
      c.code.toLowerCase() === q ||
      c.name.toLowerCase().startsWith(q)
  );
}
