import {
  Course,
  Instructor,
  Testimonial,
  FaqItem,
  PricingPlan,
  PlatformMetric,
  StudentScholar,
  CandidateStudent,
  MockExamPaper,
} from "./types";

export const MOCK_INSTRUCTORS: Record<string, Instructor> = {
  sarah: {
    id: "inst-1",
    name: "Dr. Sarah Jenkins, M.Sc.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    roleTitle: "Senior Pearson Edexcel Lead Examiner (Pure Math & Mechanics)",
    institution: "UK International Assessment Board",
    rating: 4.98,
    studentsCount: 14200,
  },
  marcus: {
    id: "inst-2",
    name: "Prof. Marcus Vance, Ph.D.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    roleTitle: "Head of London A/L Physics & Laboratory Assessment",
    institution: "Cambridge International Guild",
    rating: 4.94,
    studentsCount: 11800,
  },
  elena: {
    id: "inst-3",
    name: "Elena Rostova, B.Sc. Econ",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    roleTitle: "Chief Lecturer in London A/L Economics & Business Studies",
    institution: "London School of Economics Faculty Network",
    rating: 4.92,
    studentsCount: 9400,
  },
  david: {
    id: "inst-4",
    name: "Dr. David Chen, Ph.D.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    roleTitle: "Senior Chemistry & Biology Chief Evaluator (IAL & IGCSE)",
    institution: "Imperial College London Alumni Faculty",
    rating: 4.96,
    studentsCount: 12500,
  },
};

export const MOCK_COURSES: Course[] = [
  {
    id: "course-1",
    title: "Pearson Edexcel IAL Pure Mathematics (P1, P2, P3, P4, Mechanics & Statistics)",
    slug: "pearson-edexcel-ial-pure-mathematics-mechanics",
    subtitle: "Complete specification coverage, unit-by-unit past paper walkthroughs, and examiner mark schemes.",
    description: "Master the entire Pearson Edexcel International Advanced Level (IAL) Pure Mathematics syllabus. Covers algebraic methods, calculus, trigonometry, numerical methods, Mechanics (M1), and Statistics (S1) with full 10-year past paper walkthroughs.",
    category: "Pure Mathematics & Mechanics",
    level: "London A/L (A2 Level)",
    examBoard: "Pearson Edexcel",
    subjectCode: "WMA11 - WMA14 / WME01 / WST01",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80",
    price: 95,
    originalPrice: 160,
    rating: 4.98,
    reviewCount: 1840,
    studentsEnrolled: 8200,
    durationHours: 64,
    lessonsCount: 88,
    featured: true,
    bestseller: true,
    instructor: MOCK_INSTRUCTORS.sarah,
    tags: ["Edexcel", "London A/L", "Pure Maths", "P1-P4", "Mechanics", "Statistics"],
    skills: ["Calculus & Integration", "Trigonometric Proofs", "Kinematics & Dynamics", "Hypothesis Testing"],
  },
  {
    id: "course-2",
    title: "Pearson Edexcel IAL Physics (Units 1 to 6 Practical & Theory Masterclass)",
    slug: "pearson-edexcel-ial-physics-unit-1-to-6",
    subtitle: "Mechanics, Waves, Electric Circuits, Fields, Nuclear Radiation, and Alternative to Practical.",
    description: "A thorough examination course designed for London A/L candidates aiming for A* and A grades. Includes step-by-step solutions for Unit 1, Unit 2, Unit 3 (Practical), Unit 4, Unit 5, and Unit 6 with real laboratory video demonstrations.",
    category: "Physics (IAL & IGCSE)",
    level: "London A/L (A2 Level)",
    examBoard: "Pearson Edexcel",
    subjectCode: "WPH11 - WPH16",
    thumbnail: "https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=800&auto=format&fit=crop&q=80",
    price: 95,
    originalPrice: 160,
    rating: 4.95,
    reviewCount: 1420,
    studentsEnrolled: 6900,
    durationHours: 58,
    lessonsCount: 76,
    featured: true,
    bestseller: true,
    instructor: MOCK_INSTRUCTORS.marcus,
    tags: ["Edexcel", "London A/L", "Physics", "Units 1-6", "Past Papers"],
    skills: ["Electric & Magnetic Fields", "Quantum Phenomena", "Thermal Energy", "Lab Practical Analysis"],
  },
  {
    id: "course-3",
    title: "Pearson Edexcel IAL Chemistry (Units 1, 2, 3, 4, 5 & 6 Organic, Inorganic & Physical)",
    slug: "pearson-edexcel-ial-chemistry-unit-1-to-6",
    subtitle: "Energetics, Reaction Kinetics, Organic Mechanisms, Transition Metals, and Lab Analysis.",
    description: "Designed strictly to the Pearson Edexcel IAL specification. Master reaction mechanisms, Born-Haber cycles, NMR spectroscopy, transition metal complexes, and scored exam mock booklets.",
    category: "Chemistry (IAL & IGCSE)",
    level: "London A/L (A2 Level)",
    examBoard: "Pearson Edexcel",
    subjectCode: "WCH11 - WCH16",
    thumbnail: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80",
    price: 90,
    originalPrice: 150,
    rating: 4.96,
    reviewCount: 1180,
    studentsEnrolled: 5800,
    durationHours: 52,
    lessonsCount: 70,
    featured: true,
    bestseller: false,
    instructor: MOCK_INSTRUCTORS.david,
    tags: ["Edexcel", "London A/L", "Chemistry", "Organic Chemistry", "Spectroscopy"],
    skills: ["Reaction Mechanisms", "Equilibrium & Kinetics", "Inorganic Chemistry", "Spectroscopy Decoding"],
  },
  {
    id: "course-4",
    title: "Pearson Edexcel IAL Economics & Business Studies (Units 1 to 4 Macro & Micro)",
    slug: "pearson-edexcel-ial-economics-business-studies",
    subtitle: "Market failure, macroeconomic policy, business behavior, and international economic development.",
    description: "Learn how to write 20-mark and 25-mark evaluation essays that score top marks under Edexcel criteria. Comprehensive diagrams, data-response extract analysis, and past examiner mark scheme deconstructions.",
    category: "Economics & Business Studies",
    level: "London A/L (AS Level)",
    examBoard: "Pearson Edexcel",
    subjectCode: "WEC11 - WEC14 / WBS11 - WBS14",
    thumbnail: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80",
    price: 85,
    originalPrice: 140,
    rating: 4.92,
    reviewCount: 960,
    studentsEnrolled: 4700,
    durationHours: 44,
    lessonsCount: 60,
    featured: false,
    bestseller: true,
    instructor: MOCK_INSTRUCTORS.elena,
    tags: ["Edexcel", "London A/L", "Economics", "Business", "Macroeconomics"],
    skills: ["Essay Evaluation Structure", "Market Failure Analysis", "Fiscal & Monetary Policy", "Globalization Models"],
  },
  {
    id: "course-5",
    title: "Cambridge & Edexcel London O/L (IGCSE) Mathematics (Paper 1H & 2H Mastery)",
    slug: "cambridge-edexcel-igcse-mathematics-mastery",
    subtitle: "Numbers, Algebra, Geometry, Mensuration, Trigonometry, Vectors & Probability.",
    description: "The definitive revision program for London O/L (IGCSE) students aiming for Grade 9/8 (A*). Step-by-step walkthroughs of past papers with structured topic-by-topic drills.",
    category: "Pure Mathematics & Mechanics",
    level: "London O/L (IGCSE)",
    examBoard: "Pearson Edexcel",
    subjectCode: "4MA1 / 0580",
    thumbnail: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&auto=format&fit=crop&q=80",
    price: 75,
    originalPrice: 120,
    rating: 4.97,
    reviewCount: 2150,
    studentsEnrolled: 11200,
    durationHours: 48,
    lessonsCount: 64,
    featured: true,
    bestseller: true,
    instructor: MOCK_INSTRUCTORS.sarah,
    tags: ["Edexcel", "London O/L", "IGCSE", "Maths", "Grade 9"],
    skills: ["Algebraic Proofs", "3D Trigonometry", "Vector Geometry", "Probability Trees"],
  },
  {
    id: "course-6",
    title: "Cambridge & Edexcel London O/L (IGCSE) Human Biology & Chemistry Foundation",
    slug: "cambridge-edexcel-igcse-biology-chemistry-foundation",
    subtitle: "Cell structure, human physiology, chemical bonding, organic chemistry, and experimental skills.",
    description: "Complete preparation for IGCSE London O/L science papers. Includes experimental skills, lab questions (Paper 6 / Paper 1BR), and rapid-fire mock assessments.",
    category: "Biology & Life Sciences",
    level: "London O/L (IGCSE)",
    examBoard: "Cambridge (CAIE)",
    subjectCode: "0610 / 0620 / 4BI1 / 4CH1",
    thumbnail: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&auto=format&fit=crop&q=80",
    price: 75,
    originalPrice: 120,
    rating: 4.93,
    reviewCount: 1640,
    studentsEnrolled: 9100,
    durationHours: 46,
    lessonsCount: 62,
    featured: false,
    bestseller: false,
    instructor: MOCK_INSTRUCTORS.david,
    tags: ["Cambridge", "London O/L", "Biology", "Chemistry", "IGCSE"],
    skills: ["Enzyme Kinetics", "Genetics & Inheritance", "Stoichiometry & Moles", "Experimental Design"],
  },
];

export const MOCK_STUDENTS: StudentScholar[] = [
  {
    id: "stud-1",
    studentNumber: "ID: UK-92810A01",
    name: "Tariq Al-Mansoor",
    email: "tariq.mansoor@student.edupulse.uk",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    qualification: "London A/L (IAL)",
    examBoard: "Pearson Edexcel",
    targetSeries: "May/June 2026",
    enrolledSubjects: ["Pure Maths P1-P4", "Physics Units 1-6", "Chemistry Units 1-6"],
    mockAverage: "94.2% (A*)",
    status: "ACTIVE",
    feeStatus: "PAID",
    registeredDate: "12 Jan 2026",
  },
  {
    id: "stud-2",
    studentNumber: "ID: UK-92810A02",
    name: "Kavisha Fernando",
    email: "kavisha.f@student.edupulse.uk",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    qualification: "London A/L (IAL)",
    examBoard: "Pearson Edexcel",
    targetSeries: "May/June 2026",
    enrolledSubjects: ["Economics Units 1-4", "Business Studies", "Pure Maths P1-P2"],
    mockAverage: "88.6% (A)",
    status: "ACTIVE",
    feeStatus: "PAID",
    registeredDate: "15 Jan 2026",
  },
  {
    id: "stud-3",
    studentNumber: "ID: UK-92810A03",
    name: "Aiden Montgomery",
    email: "aiden.m@student.edupulse.uk",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    qualification: "London O/L (IGCSE)",
    examBoard: "Pearson Edexcel",
    targetSeries: "May/June 2026",
    enrolledSubjects: ["IGCSE Maths 4MA1", "IGCSE Physics 4PH1", "IGCSE Chemistry 4CH1"],
    mockAverage: "96.0% (Grade 9)",
    status: "ACTIVE",
    feeStatus: "PAID",
    registeredDate: "20 Jan 2026",
  },
  {
    id: "stud-4",
    studentNumber: "ID: UK-92810A04",
    name: "Nour El-Sayed",
    email: "nour.sayed@student.edupulse.uk",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    qualification: "London A/L (IAL)",
    examBoard: "Cambridge (CAIE)",
    targetSeries: "Oct/Nov 2026",
    enrolledSubjects: ["Biology (9700)", "Chemistry (9701)", "Pure Maths (9709)"],
    mockAverage: "91.4% (A*)",
    status: "PENDING_MOCK",
    feeStatus: "PARTIAL",
    registeredDate: "02 Feb 2026",
  },
  {
    id: "stud-5",
    studentNumber: "ID: UK-92810A05",
    name: "Ruwan Wickramasinghe",
    email: "ruwan.w@student.edupulse.uk",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    qualification: "London O/L (IGCSE)",
    examBoard: "Cambridge (CAIE)",
    targetSeries: "May/June 2026",
    enrolledSubjects: ["IGCSE Extended Maths", "IGCSE Biology", "IGCSE Economics"],
    mockAverage: "85.0% (Grade 8)",
    status: "ACTIVE",
    feeStatus: "PAID",
    registeredDate: "05 Feb 2026",
  },
];

export const MOCK_CANDIDATES = MOCK_STUDENTS;

export const MOCK_EXAM_PAPERS: MockExamPaper[] = [
  {
    id: "mock-1",
    paperCode: "WMA14/01",
    title: "Edexcel IAL Pure Mathematics P4 (Full Mock Paper 2026 Series)",
    examBoard: "Pearson Edexcel",
    level: "London A/L (IAL)",
    durationMins: 90,
    totalMarks: 75,
    submittedCount: 342,
    gradedCount: 310,
    avgPercentage: 82.4,
    releaseDate: "10 Feb 2026",
  },
  {
    id: "mock-2",
    paperCode: "WPH14/01",
    title: "Edexcel IAL Physics Unit 4: Further Mechanics, Fields & Particles",
    examBoard: "Pearson Edexcel",
    level: "London A/L (IAL)",
    durationMins: 105,
    totalMarks: 90,
    submittedCount: 285,
    gradedCount: 270,
    avgPercentage: 78.9,
    releaseDate: "12 Feb 2026",
  },
  {
    id: "mock-3",
    paperCode: "WCH12/01",
    title: "Edexcel IAL Chemistry Unit 2: Energetics, Group 2 & 7, Organic Chem",
    examBoard: "Pearson Edexcel",
    level: "London A/L (IAL)",
    durationMins: 90,
    totalMarks: 80,
    submittedCount: 215,
    gradedCount: 198,
    avgPercentage: 84.1,
    releaseDate: "14 Feb 2026",
  },
  {
    id: "mock-4",
    paperCode: "4MA1/1H",
    title: "Edexcel IGCSE Mathematics Paper 1H (Higher Tier Standardized Mock)",
    examBoard: "Pearson Edexcel",
    level: "London O/L (IGCSE)",
    durationMins: 120,
    totalMarks: 100,
    submittedCount: 460,
    gradedCount: 442,
    avgPercentage: 89.2,
    releaseDate: "15 Feb 2026",
  },
];

export const MOCK_METRICS: PlatformMetric[] = [
  {
    label: "Enrolled Scholars & Students",
    value: "28,400+",
    subtext: "London A/L (IAL) & London O/L (IGCSE)",
    growth: "+34% YoY",
  },
  {
    label: "A* & A Grade Success Rate",
    value: "96.4%",
    subtext: "Verified Academic Curriculum Results",
    growth: "Rank #1 Academy",
  },
  {
    label: "Coursework & Masterclasses",
    value: "3,800+",
    subtext: "Unit-by-Unit Topic Walkthroughs",
    growth: "2015-2026 Curriculum",
  },
  {
    label: "Academic Partner Centers",
    value: "140+",
    subtext: "International Academic Partner Colleges",
    growth: "UK Recognized",
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Tariq Al-Mansoor",
    role: "London A/L Scholar (4 A* Achieved)",
    affiliation: "Admitted to Imperial College London (Mechanical Engineering)",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    content: "The Pure Maths P1-P4 and Physics Unit 1-6 walkthroughs were the exact reason I got 4 A*s. The lecturer breakdowns showed exactly where students master calculus and theory proofs.",
    rating: 5,
    userType: "STUDENT",
    verifiedCourse: "London A/L Pure Mathematics & Physics",
  },
  {
    id: "test-2",
    name: "Dr. Sarah Jenkins",
    role: "Senior Academic Lecturer in Mathematics",
    affiliation: "Chief Lecturer in Pure Mathematics & Mechanics",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    content: "Our goal is simple: ensure every student understands the curriculum inside out. EduPulse provides students with interactive step-by-step video proofs and instant teacher remarks.",
    rating: 5,
    userType: "INSTRUCTOR",
  },
  {
    id: "test-3",
    name: "Alastair Vance, M.Ed.",
    role: "Chief Academic Registrar & Academy Dean",
    affiliation: "London International Academy Network",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    content: "Administering student registrations, coursework grading queues, and tracking syllabus progress across 140 academic centers has never been smoother.",
    rating: 5,
    userType: "ADMIN",
  },
];

export const MOCK_PRICING: PricingPlan[] = [
  {
    id: "tier-student",
    name: "Scholar Pro (Single Subject)",
    badge: "Most Popular",
    description: "Full unit specification access, live interactive seminars, video lesson vaults, and solution guides.",
    monthlyPrice: 25,
    annualPrice: 20,
    popular: true,
    roleTarget: "Individual Scholar (O/L or A/L)",
    ctaText: "Enroll in Subject",
    features: [
      "Full unit topic video lectures",
      "Comprehensive video theory vaults",
      "Full Coursework Assessments with faculty marking",
      "Downloadable unit summary notes & formula sheets",
      "Live weekly faculty Q&A & problem solving sessions",
      "Complete Coursework Rubrics for Spring/Summer Series",
    ],
  },
  {
    id: "tier-instructor",
    name: "Triple Science & Maths Bundle",
    description: "Complete all-in-one package for London A/L (Maths, Physics, Chemistry) or London O/L.",
    monthlyPrice: 65,
    annualPrice: 50,
    popular: false,
    roleTarget: "Full A/L or O/L Student",
    ctaText: "Get Full A/L Science Bundle",
    features: [
      "Access to all 3 A/L or O/L Science/Commerce subjects",
      "Weekly live seminar classes with Senior Faculty",
      "Unlimited Coursework submissions & detailed feedback",
      "Priority 24/7 AI & Tutor doubt-solving assistance",
      "Complete Virtual Laboratory & Practical video demonstrations",
      "University Admissions & UCAS Personal Statement review",
    ],
  },
  {
    id: "tier-enterprise",
    name: "Institutional Campus License",
    badge: "Institutional Center",
    description: "For international schools, academic partner colleges, and private tutoring institutes.",
    monthlyPrice: 199,
    annualPrice: 169,
    popular: false,
    roleTarget: "International School / College",
    ctaText: "Register Center",
    features: [
      "Multi-Campus Dean & Admin Command Console",
      "Unlimited student roster management",
      "Automated coursework grading & grade boundary distribution",
      "Single Sign-On (SAML 2.0, Microsoft Azure, Google)",
      "Dedicated School Academic Director & Training",
      "Custom branded portal with full curriculum analytics",
    ],
  },
];

export const MOCK_FAQS: FaqItem[] = [
  {
    id: "faq-1",
    category: "General",
    question: "Are your courses strictly aligned with London A/L & O/L specifications?",
    answer: "Yes! All courses are mapped 100% to international London A/L and O/L curriculum specifications, taught by experienced Senior Faculty Lecturers.",
  },
  {
    id: "faq-2",
    category: "Assessments",
    question: "Do you provide coursework assessments with teacher evaluations?",
    answer: "Yes. Every unit includes standardized coursework assessments. When students submit their solutions, our verified faculty grade them against official academic rubrics with detailed margin remarks.",
  },
  {
    id: "faq-3",
    category: "London A/L",
    question: "How do you prepare students for laboratory and practical units?",
    answer: "We offer dedicated high-definition video laboratory walkthroughs demonstrating required core practicals, error analysis calculations, graph plotting standards, and uncertainty estimation.",
  },
  {
    id: "faq-4",
    category: "Admissions",
    question: "Can independent students and distance learners use this platform?",
    answer: "Absolutely. Thousands of independent scholars and distance learners use EduPulse as their complete primary study and academic learning academy.",
  },
  {
    id: "faq-5",
    category: "Academic",
    question: "What qualifications are covered on EduPulse?",
    answer: "We specialize in London A/L (IAL AS & A2), London O/L (IGCSE), GCE Advanced Levels, and specialized subject curriculum masterclasses.",
  },
];
